name: greeter
main: ./index
version: 0.0.0
devDependencies:
  tape: ~1.0.0
author: ishiduca@gmail.com
license: MIT
testling:
  files: t/*.js
  browsers:
    - ie/6..latest
    - chrome/20..latest
    - ff/3.5..latest
    - safari/latest
    - opera/11.0..latest
    - android-browser/4.2
    - iphone/6.0..latest
    - ipad/6.0..latest
